[tool.isort]
line_length = 88
profile = "black"

[tool.mypy]
disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = [
    'bar_chart_race',
    'fire',
    'requests',
]
ignore_missing_imports = true